services:
  express:
    image: tylereck81/express-app:latest
    ports:
      - 8080:8080
    container_name: express-test
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: express-test
    container_name: watchtower
    
